### ISSUE TITLE
Does this have issues with different keyboard layout?

### ISSUE THREAD

**Issue by devingDev** [whid-injector/WHID#20]
Hi I can't find much info like how much storage and so on it has , but I want to know if it works even if you have a different keyboard layout.

I tried a digispark with german keyboard layout in windows and it mistypes many things, resulting in bad and wrong words and chars-

**Comment by whid-injector** [comment]
in the web UI is written the space used and left.
About layout, read the wiki!
https://github.com/whid-injector/WHID/wiki/Keyboards-Layout
