### ISSUE TITLE
Changing keyboard layout

### ISSUE THREAD

**Issue by TheNerdOne9** [whid-injector/WHID#33]
Could someone explain me how can i change the keyboard layout, there's any tutorial? I never played with arduino before ... Thanks!

**Comment by whid-injector** [comment]
Tell me one thing... 
I see you are able to write... but I believe you are not that smart in reading... right?
https://github.com/whid-injector/WHID/wiki/Keyboards-Layout

P.S. If you never played with arduino.... is time to learn!
