### ISSUE TITLE
White screen on WHID Mobile Connector app.

### ISSUE THREAD

**Issue by Krack1n** [whid-injector/WHID#54]
Hi,
I am using a nexus 5 rooted with kali nethunter installed on it and my WHID connector app has stopped working. When I open it all it shows is a the logo and then a blank white screen. Any one have any ideas on how to fix this? 
Thank you.

**Comment by whid-injector** [comment]
Please open the issue on https://github.com/whid-injector/WHID-Mobile-Connector
