### ISSUE TITLE
WHID LED Blink Command

### ISSUE THREAD

**Issue by SyVDA** [whid-injector/WHID#58]
Hello All, suggestion/question. 

I was wondering if there is a command that can be input to blink the LED. This way once a payload has been run a visual queue of one or three LED blinks can be added to the end of the script for visual confirmation of a completed script.

**Comment by minkione** [comment]
```
Blink LED:
--"BlinkLED:X"
--X=# of times to blink the LED 750ms ON 500ms OFF
--"BlinkLED:3" Blinks the LED 3 times
--Useful for knowing what stage of a payload you are on(add to the end of payload).
```
