### ISSUE TITLE
Impossible to unbrik the device

### ISSUE THREAD

**Issue by rauburtin** [whid-injector/WHID#75]
Hello,
I would like to reset the device because I broke the ui interface when I flashed it.
I read all the documentation and I didn't find a way to unbrik the device (I used this method https://swisskyrepo.github.io/WhidInjector/).
I tried also to upload the firmware with esptool but I have always the same error (impossible to connect).
any help would be appreciated.

Best

**Comment by rauburtin** [comment]
Hello
I found a way to unbrik the device

**Comment by GabrielSestieri** [comment]
Could you maybe share the solution you found?
