### ISSUE TITLE
Storage Full

### ISSUE THREAD

**Issue by MooonShot** [whid-injector/WHID#9]
Hey I flashed with the Wifi Duck bin file after watching your video, I successfully flashed that but When I connect to AP I can't upload scripts It says storage full and Format button is not working

![screen shot 2017-06-10 at 7 13 58 pm](https://user-images.githubusercontent.com/20306382/27003280-3e239fca-4e11-11e7-96d8-238338ea2640.png)

**Comment by whid-injector** [comment]
You made some mistake for sure.
And also check how to open tickets!!!
Read ot all carefully!
https://github.com/whid-injector/WHID/wiki

**Comment by whid-injector** [comment]
This issue shows that the FS in the ESP didn't get initialized/formatted properly.
You have to follow exactly how is showed in the video. With the same settings.
If still persists might be your Arduino Version or the fact you use a USB 3.0 port.

About the reset Hall sensor it works. You just need to get used to it. (And of course, u need a magnet)

**Comment by MooonShot** [comment]
I did everything stated in video, I have USB 2.0 and It's not letting me upload payload with your firmware. This thing does not work. I need refund!

**Comment by whid-injector** [comment]
1) I am NOT the seller and I have ZERO profit on it.
2) Is like 99.99999% impossible is a defective piece. 
3) I have tested 20+ devices and so far NO ONE broken. At most I had to reset it.
4) If people is not skilled enough to understand how one opensource  gadget works... better don't buy and waste time of other people. 🤝

So far you are the first I see with this issue.

**Comment by MooonShot** [comment]
I very well know how gadget works, Any way to replace my product ?

**Comment by whid-injector** [comment]
Read point 1) and 4) again.

**Comment by MooonShot** [comment]
_/\_

**Comment by whid-injector** [comment]
Try contact the seller and proove them the HW is faulty.
